version: '3.7'

services:
  moonbeam-bot:
    container_name: moonbeam-bot
    build: .
    image: jonheese/moonbeam-bot:latest
    volumes:
      - type: bind
        source: ./quotes.json
        target: /usr/src/app/quotes.json
      - type: bind
        source: ./config.json
        target: /usr/src/app/config.json
      - type: bind
        source: ./words.json
        target: /usr/src/app/words.json
      - type: bind
        source: ./perds.json
        target: /usr/src/app/perds.json
    network_mode: "bridge"
    restart: always
