quotes = [
             "I never cuss at the clients. I am like fuckin' sugar with the clients. Like fuckin' silken brown sugar - Jim DeHart",
             "I wouldn't grab your junk, why would you put your fingers between my toes? - Jim DeHart, on one of the great mysteries of the universe",
             "If you need laptop internet, go to www.cheddar.figtits.inetu.net. - Jason Chamiak, helping INetU employees to excel wirelessly",
             "I mean yeah, it could suck a shit-ton of dick and we could fuck ourselves, but it could also be our knight in shining armor. - Andrew Widdersheim, on centralized Bacula",
             "Let me know if I can offer any more existence - Jim DeHart, always keepin' it real",
             "I have a bunch of those at home. They're good for puttin' shit on - Jim DeHart, in reference to a table",
             "Anything's better with turds. - Bill Pfeiffer",
             "You know, if we were at Ichiban we could get some third-rate catfood flipped over on a hotplate in front of us. - Andy Barnett, on Asian food",
             "These people are like, 'Oh my god, it's the biggest thing ever, Oh my god, it's the sweetest taste!'  But I'm like, 'no, I'm going to my destination.' - Bill Pfeiffer, a man who loves extended metaphors",
             "You know, I got the three monitors, my shit nestles in between, I don't gotta be all cock-eyed and shit. - Bill Pfeiffer, on proper office ergonomics",
             "I wrote it down in my brain. - Jim DeHart, when asked if he wrote something down, totally serious",
             "If he had someone to micro-manage him, he'd be like, really valuable. - Chris Mikolay, on strategies for maximizing staff effectiveness",
             "But I eat raw meat all the time, and it's fine. - Jim DeHart, on food poisoning",
             "Like, I tell people to fuck off a lot. Sometimes it's okay, sometimes it's not. - Andrew Widdersheim",
             "I made some great life choices, like, I get to live with my parents at 30, and I can buy a go-kart whenever I want. - Chris Mikolay",
             "You am, or you have? - Andy Barnett, demonstrating a solid grasp of his native tongue, the Queen's English",
             "When you see something come from that human being, help as much as you can, but don't waste a lot of your time, because you're never gonna get that back. - Bill Pfeiffer, on helping \"human beings\"",
             "When you say 'put whatever the fuck we want to put in there,' what is 'the fuck' that we would want to put in there? - Andy Barnett, drilling down to extreme levels of detail",
             "Say it again. Say what you're saying. - Bill Pfeiffer, trying to catch up on a conversation after not paying attention for a few moments",
             "Why do I want a burrito?  It's like a-- it's like a flour-y bag of sweat. - Andy Barnett",
             "Everything's a generalization! - Jim DeHart, the master of reflexive references",
             "Was that the movie with David DiCaprio? - Jim DeHart, referring to a movie starring neither David Duchovny nor Leonardo DiCaprio",
             "You have to suck the heads, or you don't get invited back. - Jon Heese, on crawfish boils, no really",
             "Sorry, you're welcome! - Chris Mikolay, explaining to a hypothetical client why their successful backups run slowly.",
             "It's like I cannot not be a dick. - Bill Pfeiffer, on talking to a specific (unnamed) colleague",
             "We just need to drop that expectation that everybody is going to perform at that level. Like, I'm gonna be honest: 99% of people are retarded. - Bill Pfeiffer, Motivational Speaker",
             "East German, that's kinda Russian. - Jim DeHart, geography expert",
	     "They're like really expensive pens, but they don't write very expensive - like - more. - Chris Mikolay, on Cross pens",
             "Shirts are like fingerless gloves for your body. - Jon Heese",
             "The poop goes down and the pee goes up - Bill Pfeiffer, on what happens when you're on a liquid diet",
             "Please do not die on shit hill. - Nick Selpa, to Bill Pfeiffer",
             "Jesus Christ, this fucking toilet seat just shot forward and almost chopped my dick off! - Jim DeHart",
             "Are you sure you know what you are talking about? - Jeremy Palmer, to Karin Davies, Senior Vice President, Human Resources",
             "It's the middle porridge; it's the just-right shit. - Bill Pfeiffer, on selecting the right tool for the job",
             "There's more that are geniuses, but there's also more that are retards. - Mark Rekai, on men",
             "They sell clothes - like who the hell buys a dress at Cracker Barrel? I'm guessing life's different South of the Mason Dixon line... - Andy Barnett",
             "We snort the coke, piss some out, fish eat the piss, then we eat the fish. - Jim DeHart, on his Saturday night plans?",
         ]
